version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.9-alpine
    networks:
      - app-network
    
  redis:
    image: redis:alpine
    networks:
      - app-network

  screenshot:
    build: ./screenshot_service
    command: nodemon server.js
    networks:
      - app-network
    links:
      - rabbitmq
    
  frontend:
    build: ./frontend
    command: nodemon server.js
    ports:
      - "5000:80"
    networks:
      - app-network
    links:
      - rabbitmq

networks:
  app-network:
    driver: bridge